### ISSUE TITLE
Install JAVA

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-bionic64-ansible-docker#3]
**Originally posted in [vagrant-hashistack#issue304](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/304)**

## Why
Working with [terrafrom-nomad-presto]() module, I have needs to automate table creation process with [presto-cli](https://prestosql.io/docs/current/installation/cli.html)

Presto-cli is `jar` file

## Log
```text
vagrant@vagrant:/vagrant/dev/ansible$ ../../presto_340 --server localhost:8080 --catalog hive --schema default --user presto --file ../../example/resources/query/csv_create_table.sql
../../presto_340: 3: exec: java: not found
vagrant@vagrant:/vagrant/dev/ansible$ which java
vagrant@vagrant:/vagrant/dev/ansible$ echo $JAVA_HOME

vagrant@vagrant:/vagrant/dev/ansible$
```

## Notes
I have successfully tested [presto release 340](https://repo1.maven.org/maven2/io/prestosql/presto-cli/340/) with openjdk 11.0.8.
```text
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

**Comment by pdmthorsrud** [comment]
I see I am a little late to this, but could we possibly use presto's API to do all of this? 
Doing changes all the way down in the base-box makes it bloated. This is meant to solve something fairly specific that we as a team are doing, and not something all people using this base-box would want, which is why I don't think it should be something that's done in the base-box. Any thoughts?

**Comment by zhenik** [comment]
> I see I am a little late to this, but could we possibly use presto's API to do all of this?
> Doing changes all the way down in the base-box makes it bloated. This is meant to solve something fairly specific that we as a team are doing, and not something all people using this base-box would want, which is why I don't think it should be something that's done in the base-box. Any thoughts?

## Option 1
To be able to connect to presto remotely we have to use presto cli. Presto-cli is a jar file. Jar file requires java installed on the machine.

## Option 2
Use terraform and copy file contents to nomad-job using `template` stanza. 

IMHO. -> option 2 takes a longer time to develop

**Comment by pdmthorsrud** [comment]
> ## Option 1
> To be able to connect to presto remotely we have to use presto cli. Presto-cli is a jar file. Jar file requires java installed on the machine.

Why do you have to use the presto-cli? Could you open a proxy and POST to presto? https://github.com/prestosql/presto/wiki/HTTP-Protocol

**Comment by zhenik** [comment]
@pdmthorsrud nice. I totally forgot about REST API, I will check it, thx.

**Comment by zhenik** [comment]
Thx to @pdmthorsrud for docker solution, without need to install JAVA on the base box. Close.
