### ISSUE TITLE
Move ownership to Skatteetaten GitHub

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-bionic64-ansible-docker#6]
This repository is packer base image of [vagrant-hashistack](https://github.com/Skatteetaten/vagrant-hashistack)

@fredrikhgrelland You might need to transfer ownership to [Skatteetaten](https://github.com/Skatteetaten)

**Comment by claesgill** [comment]
@fredrikhgrelland Any update on this?

**Comment by fredrikhgrelland** [comment]
This repo needs a review and cleanup before moving

**Comment by fredrikhgrelland** [comment]
Will archive. Not needed anymore from https://github.com/Skatteetaten/vagrant-hashistack/releases/tag/0.11.0
